// Déven Estève / Romain Lavidalie

const characterInformations = [{
    id: 0,
    name: "Mario",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Mario Finale",
    neutralB: "Fireball",
    sideB: "Cape",
    upB: "Super Jump Punch",
    downB: "F.L.U.D.D."
  },
  {
    id: 1,
    name: "Donkey Kong",
    initGame: "Donkey Kong",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Jungle Rush",
    neutralB: "Giant Punch",
    sideB: "Headbutt",
    upB: "Spinning Kong",
    downB: "Hand Slap"
  },
  {
    id: 2,
    name: "Link",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Ancient Bow and Arrow",
    neutralB: "Bow and Arrows",
    sideB: "Boomerang",
    upB: "Spin Attack",
    downB: "Remote Bomb"
  },
  {
    id: 3,
    name: "Samus",
    initGame: "Metroid",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Zero Laser",
    neutralB: "Charge Shot",
    sideB: "Missile",
    upB: "Screw Attack",
    downB: "Bomb"
  },
  {
    id: 4,
    name: "Dark Samus",
    initGame: "Metroid",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Phazon Laser",
    neutralB: "Charge Shot",
    sideB: "Missile",
    upB: "Screw Attack",
    downB: "Bomb"
  },
  {
    id: 5,
    name: "Yoshi",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Stampede!",
    neutralB: "Egg Lay",
    sideB: "Egg Roll",
    upB: "Egg Throw",
    downB: "Yoshi Bomb"
  },
  {
    id: 6,
    name: "Kirby",
    initGame: "Kirby",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Ultra Sword",
    neutralB: "Inhale",
    sideB: "Hammer Flip",
    upB: "Final Cutter",
    downB: "Stone"
  },
  {
    id: 7,
    name: "Fox",
    initGame: "Star Fox",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Team Star Fox",
    neutralB: "Blaster",
    sideB: "Fox Illusion",
    upB: "Fire Fox",
    downB: "Reflector"
  },
  {
    id: 8,
    name: "Pikachu",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Volt Tackle",
    neutralB: "Thunder Jolt",
    sideB: "Skull Bash",
    upB: "Quick Attack",
    downB: "Thunder"
  },
  {
    id: 9,
    name: "Luigi",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Poltergust G-00",
    neutralB: "Fireball",
    sideB: "Green Missile",
    upB: "Super Jump Punch",
    downB: "Luigi Cyclone"
  },
  {
    id: 10,
    name: "Ness",
    initGame: "Earthbound",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "PK Starstorm",
    neutralB: "PK Flash",
    sideB: "PK Fire",
    upB: "PK Thunder",
    downB: "PSI Magnet"
  },
  {
    id: 11,
    name: "Captain Falcon",
    initGame: "F-Zero",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Blue Falcon",
    neutralB: "Falcon Punch",
    sideB: "Raptor Boost",
    upB: "Falcon Dive",
    downB: "Falcon Kick"
  },
  {
    id: 12,
    name: "Jigglypuff",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros.",
    finalSmash: "Puff Up",
    neutralB: "Rollout",
    sideB: "Pound",
    upB: "Sing",
    downB: "Rest"
  },
  {
    id: 13,
    name: "Peach",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Peach Blossom",
    neutralB: "Toad",
    sideB: "Peach Bomber",
    upB: "Peach Parasol",
    downB: "Vegetable"
  },
  {
    id: 14,
    name: "Daisy",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Daisy Blossom",
    neutralB: "Toad",
    sideB: "Daisy Bomber",
    upB: "Daisy Parasol",
    downB: "Vegetable"
  },
  {
    id: 15,
    name: "Bowser",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Giga Bowser Punch",
    neutralB: "Fire Breath",
    sideB: "Flying Slam",
    upB: "Whirling Fortress",
    downB: "Bowser Bomb"
  },
  {
    id: 16,
    name: "Ice Climbers",
    initGame: "Ice Climber",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Iceberg",
    neutralB: "Ice Shot",
    sideB: "Squall Hammer",
    upB: "Belay",
    downB: "Blizzard"
  },
  {
    id: 17,
    name: "Sheik",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Sheikah Dance",
    neutralB: "Needle Storm",
    sideB: "Burst Grenade",
    upB: "Vanish",
    downB: "Bouncing Fish"
  },
  {
    id: 18,
    name: "Zelda",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Triforce of Wisdom",
    neutralB: "Nayru\'s Love",
    sideB: "Din\'s Fire",
    upB: "Farore\'s Wind",
    downB: "Phantom Slash"
  },
  {
    id: 19,
    name: "Dr. Mario",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Doctor Finale",
    neutralB: "Megavitamins",
    sideB: "Super Sheet",
    upB: "Super Jump Punch",
    downB: "Dr. Tornado"
  },
  {
    id: 20,
    name: "Pichu",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Volt Tackle",
    neutralB: "Thunder Jolt",
    sideB: "Skull Bash",
    upB: "Agility",
    downB: "Thunder"
  },
  {
    id: 21,
    name: "Falco",
    initGame: "Star Fox",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Team Star Fox",
    neutralB: "Blaster",
    sideB: "Falco Phantasm",
    upB: "Fire Bird",
    downB: "Reflector"
  },
  {
    id: 22,
    name: "Marth",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Critical Hit",
    neutralB: "Shield Breaker",
    sideB: "Dancing Blade",
    upB: "Dolphin Slash",
    downB: "Counter"
  },
  {
    id: 23,
    name: "Lucina",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Critical Hit",
    neutralB: "Shield Breaker",
    sideB: "Dancing Blade",
    upB: "Dolphin Slash",
    downB: "Counter"
  },
  {
    id: 24,
    name: "Young Link",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Triforce Slash",
    neutralB: "Fire Bow",
    sideB: "Boomerang",
    upB: "Spin Attack",
    downB: "Bomb"
  },
  {
    id: 25,
    name: "Ganondorf",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Ganon, The Demon King",
    neutralB: "Warlock Punch",
    sideB: "Flame Choke",
    upB: "Dark Dive",
    downB: "Wizard\'s Foot"
  },
  {
    id: 26,
    name: "Mewtwo",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Psystrike",
    neutralB: "Shadow Ball",
    sideB: "Confusion",
    upB: "Teleport",
    downB: "Disable"
  },
  {
    id: 27,
    name: "Roy",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Critical Hit",
    neutralB: "Flare Blade",
    sideB: "Double-Edged Dance",
    upB: "Blazer",
    downB: "Counter"
  },
  {
    id: 28,
    name: "Chrom",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Awakening Aether",
    neutralB: "Flare Blade",
    sideB: "Double-Edged Dance",
    upB: "Soaring Slash",
    downB: "Counter"
  },
  {
    id: 29,
    name: "Mr. Game And Watch",
    initGame: "Mr. Game And Watch",
    appearedFirst: "Super Smash Bros. Melee",
    finalSmash: "Octopus",
    neutralB: "Chef",
    sideB: "Judge",
    upB: "Fire",
    downB: "Oil Panic"
  },
  {
    id: 30,
    name: "Meta Knight",
    initGame: "Kirby",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Darkness Illusion",
    neutralB: "Mach Tornado",
    sideB: "Drill Rush",
    upB: "Shuttle Loop",
    downB: "Dimensional Cape"
  },
  {
    id: 31,
    name: "Pit",
    initGame: "Kid Icarus",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Lightning Chariot",
    neutralB: "Palutena Bow",
    sideB: "Upperdash Arm",
    upB: "Power of Flight",
    downB: "Guardian Orbitars"
  },
  {
    id: 32,
    name: "Dark Pit",
    initGame: "Kid Icarus",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Dark Pit Staff",
    neutralB: "Silver Bow",
    sideB: "Electroshock Arm",
    upB: "Power of Flight",
    downB: "Guardian Orbitars"
  },
  {
    id: 33,
    name: "Zero Suit Samus",
    initGame: "Metroid",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Zero Laser",
    neutralB: "Paralyzer",
    sideB: "Plasma Whip",
    upB: "Boost Kick",
    downB: "Flip Jump"
  },
  {
    id: 34,
    name: "Wario",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Wario Man",
    neutralB: "Chomp",
    sideB: "Wario Bike",
    upB: "Corkscrew",
    downB: "Wario Waft"
  },
  {
    id: 35,
    name: "Snake",
    initGame: "Metal Gear Solid",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Covering Fire",
    neutralB: "Hand Grenade",
    sideB: "Remote Missile",
    upB: "Cypher",
    downB: "C4"
  },
  {
    id: 36,
    name: "Ike",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Great Aether",
    neutralB: "Eruption",
    sideB: "Quick Draw",
    upB: "Aether",
    downB: "Counter"
  },
  {
    id: 37,
    name: "Pokemon Trainer",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Triple Finish",
    neutralB: "Water Gun \/ Bullet Seed \/ Flamethrower",
    sideB: "Withdraw \/ Razor Leaf \/ Flare Blitz",
    upB: "Waterfall \/ Vine Whip \/ Fly",
    downB: "PokÃ©mon Change"
  },
  {
    id: 38,
    name: "Diddy Kong",
    initGame: "Donkey Kong",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Hyper Rocketbarrel",
    neutralB: "Peanut Popgun",
    sideB: "Monkey Flip",
    upB: "Rocketbarrel Boost",
    downB: "Banana Peel"
  },
  {
    id: 39,
    name: "Lucas",
    initGame: "Earthbound",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "PK Starstorm",
    neutralB: "PK Freeze",
    sideB: "PK Fire",
    upB: "PK Thunder",
    downB: "PSI Magnet"
  },
  {
    id: 40,
    name: "Sonic",
    initGame: "Sonic The Hedgehog",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Super Sonic",
    neutralB: "Homing Attack",
    sideB: "Spin Dash",
    upB: "Spring Jump",
    downB: "Spin Charge"
  },
  {
    id: 41,
    name: "King Dedede",
    initGame: "Kirby",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Dede-rush",
    neutralB: "Inhale",
    sideB: "Gordo Throw",
    upB: "Super Dedede Jump",
    downB: "Jet Hammer"
  },
  {
    id: 42,
    name: "Olimar",
    initGame: "Pikmin",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "End of Day",
    neutralB: "Pikmin Pluck",
    sideB: "Pikmin Throw",
    upB: "Winged Pikmin",
    downB: "Pikmin Order"
  },
  {
    id: 43,
    name: "Lucario",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Aura Storm",
    neutralB: "Aura Sphere",
    sideB: "Force Palm",
    upB: "Extreme Speed",
    downB: "Double Team"
  },
  {
    id: 44,
    name: "R.O.B.",
    initGame: "Famicom Accessory",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Guided Robo Beam",
    neutralB: "Robo Beam",
    sideB: "Arm Rotor",
    upB: "Robo Burner",
    downB: "Gyro"
  },
  {
    id: 45,
    name: "Toon Link",
    initGame: "The Legend of Zelda",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Triforce Slash",
    neutralB: "Hero's Bow",
    sideB: "Boomerang",
    upB: "Spin Attack",
    downB: "Bomb"
  },
  {
    id: 46,
    name: "Wolf",
    initGame: "Star Fox",
    appearedFirst: "Super Smash Bros. Brawl",
    finalSmash: "Team Star Wolf",
    neutralB: "Blaster",
    sideB: "Wolf Flash",
    upB: "Fire Wolf",
    downB: "Reflector"
  },
  {
    id: 47,
    name: "Villager",
    initGame: "Animal Crossing",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Dream Home",
    neutralB: "Pocket",
    sideB: "Lloid Rocket",
    upB: "Balloon Trip",
    downB: "Timber"
  },
  {
    id: 48,
    name: "Mega Man",
    initGame: "Mega Man",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Mega Legends",
    neutralB: "Metal Blade",
    sideB: "Crash Bomber",
    upB: "Rush Coil",
    downB: "Leaf Shield"
  },
  {
    id: 49,
    name: "Wii Fit Trainer",
    initGame: "Wii Fit",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Wii Fit",
    neutralB: "Sun Salutation",
    sideB: "Header",
    upB: "Super Hoop",
    downB: "Deep Breathing"
  },
  {
    id: 50,
    name: "Rosalina And Luma",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Grand Star",
    neutralB: "Luma Shot",
    sideB: "Star Bits",
    upB: "Launch Star",
    downB: "Gravitational Pull"
  },
  {
    id: 51,
    name: "Little Mac",
    initGame: "Punch-Out!!",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Giga Mac Rush",
    neutralB: "Straight Lunge",
    sideB: "Jolt Haymaker",
    upB: "Rising Uppercut",
    downB: "Slip Counter"
  },
  {
    id: 52,
    name: "Greninja",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Secret Ninja Attack",
    neutralB: "Water Shuriken",
    sideB: "Shadow Sneak",
    upB: "Hydro Pump",
    downB: "Substitute"
  },
  {
    id: 53,
    name: "Mii Fighter",
    initGame: "Mii Plaza",
    appearedFirst: "Super Smash Bros. 4"
  },
  {
    id: 54,
    name: "Palutena",
    initGame: "Kid Icarus",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Black Hole Laser",
    neutralB: "Autoreticle",
    sideB: "Explosive Flame",
    upB: "Warp",
    downB: "Counter/Reflect Barrier"
  },
  {
    id: 55,
    name: "Pac-Man",
    initGame: "Pac-Man",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Super PAC-MAN",
    neutralB: "Bonus Fruit",
    sideB: "Power Pellet",
    upB: "Pac-Jump",
    downB: "Fire Hydrant"
  },
  {
    id: 56,
    name: "Robin",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Pair Up",
    neutralB: "Thunder",
    sideB: "Arcfire",
    upB: "Elwind",
    downB: "Nosferatu"
  },
  {
    id: 57,
    name: "Shulk",
    initGame: "Xenoblade",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Chain Attack",
    neutralB: "Monado Arts",
    sideB: "Back Slash",
    upB: "Air Slash",
    downB: "Vision"
  },
  {
    id: 58,
    name: "Bowser Jr.",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Shadow Mario Paint",
    neutralB: "Clown Cannon",
    sideB: "Clown Kart Dash",
    upB: "Abandon Ship",
    downB: "Mechakoopa"
  },
  {
    id: 59,
    name: "Duck Hunt",
    initGame: "Duck Hunt",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "NES Zapper Posse",
    neutralB: "Trick Shot",
    sideB: "Clay Shooting",
    upB: "Duck Jump",
    downB: "Wild Gunman"
  },
  {
    id: 60,
    name: "Ryu",
    initGame: "Street Fighter",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Shin Shoryuken / Shinku Hadoken",
    neutralB: "Hadoken",
    sideB: "Tatsumaki Senpukyaku",
    upB: "Shoryuken",
    downB: "Focus Attack"
  },
  {
    id: 61,
    name: "Ken",
    initGame: "Street Fighter",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Shippu Jinraikyaku / Shinryuken",
    neutralB: "Hadoken",
    sideB: "Tatsumaki Senpukyaku",
    upB: "Shoryuken",
    downB: "Focus Attack"
  },
  {
    id: 62,
    name: "Cloud",
    initGame: "Final Fantasy",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Omnislash",
    neutralB: "Blade Beam",
    sideB: "Cross Slash",
    upB: "Climhazzard",
    downB: "Limit Charge / Finishing Touch"
  },
  {
    id: 63,
    name: "Corrin",
    initGame: "Fire Emblem",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Torrential Roar",
    neutralB: "Dragon Fang Shot",
    sideB: "Dragon Lunge",
    upB: "Dragon Ascent",
    downB: "Counter Surge"
  },
  {
    id: 64,
    name: "Bayonetta",
    initGame: "Bayonetta",
    appearedFirst: "Super Smash Bros. 4",
    finalSmash: "Infernal Climax",
    neutralB: "Bullet Climax",
    sideB: "Heel Slide / After Burner Kick",
    upB: "Witch Twist",
    downB: "Witch Time"
  },
  {
    id: 65,
    name: "Inkling",
    initGame: "Splatoon",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Killer Wail",
    neutralB: "Splattershot",
    sideB: "Splat Roller",
    upB: "Super Jump",
    downB: "Splat Bomb"
  },
  {
    id: 66,
    name: "Ridley",
    initGame: "Metroid",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Plasma Scream",
    neutralB: "Plasma Breath",
    sideB: "Space Pirate Rush",
    upB: "Wing Blitz",
    downB: "Skewer"
  },
  {
    id: 67,
    name: "Simon",
    initGame: "Castlevania",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Grand Cross",
    neutralB: "Axe",
    sideB: "Cross",
    upB: "Uppercut",
    downB: "Holy Water"
  },
  {
    id: 68,
    name: "Richter",
    initGame: "Castlevania",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Grand Cross",
    neutralB: "Axe",
    sideB: "Cross",
    upB: "Uppercut",
    downB: "Holy Water"
  },
  {
    id: 69,
    name: "King K. Rool",
    initGame: "Donkey Kong",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Blast-o-Matic",
    neutralB: "Blunderbuss",
    sideB: "Crownerang",
    upB: "Propellerpack",
    downB: "Gut Check"
  },
  {
    id: 70,
    name: "Isabelle",
    initGame: "Animal Crossing",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Dream Town Hall",
    neutralB: "Pocket",
    sideB: "Fishing Rod",
    upB: "Balloon Trip",
    downB: "Lloid Trap"
  },
  {
    id: 71,
    name: "Incineroar",
    initGame: "Pokemon",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Max Malicious Moonsault",
    neutralB: "Darkest Lariat",
    sideB: "Alolan Whip",
    upB: "Cross Chop",
    downB: "Revenge"
  },
  {
    id: 72,
    name: "Piranha Plant",
    initGame: "Super Mario",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Petey Piranha",
    neutralB: "Ptooie",
    sideB: "Poison Breath",
    upB: "Piranhacopter",
    downB: "Long-Stem Strike"
  },
  {
    id: 73,
    name: "Joker",
    initGame: "Persona",
    appearedFirst: "Super Smash Bros. Ultimate",
    finalSmash: "Coming soon",
    neutralB: "Coming soon",
    sideB: "Coming soon",
    upB: "Coming soon",
    downB: "Coming soon"
  },
];

function parseStr(str) {
  return str.toLowerCase().replace(/([^A-z])/g, '');
}

// Securing the const
window.addEventListener("load", function() {
  Object.freeze(characterInformations);
  for (var i = 0; i < characterInformations.length; i++) {
    Object.freeze(characterInformations[i]);
  }
});
